# Generated by Django 2.2.3 on 2019-09-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userstripe',
        ),
    ]
