# Generated by Django 2.2.3 on 2019-07-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url_height', models.PositiveIntegerField(default=50)),
                ('url_width', models.PositiveIntegerField(default=50)),
                ('image', models.ImageField(height_field='url_height', upload_to='Images', width_field='url_width')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('size', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=250)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(max_length=250)),
                ('classification', models.CharField(max_length=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='Shop.Supplier')),
            ],
        ),
    ]
