# Generated by Django 2.2.2 on 2019-06-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
