# Generated by Django 2.2.2 on 2019-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./customers/Images/8164687_xxl.jpg')),
                ('name', models.CharField(default='', max_length=300)),
                ('seller', models.CharField(max_length=100)),
                ('price', models.IntegerField(default='0')),
            ],
        ),
    ]
