# Generated by Django 2.2.2 on 2019-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
