# Generated by Django 2.2.2 on 2019-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20190624_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='./customers/media/Images'),
        ),
    ]
