# Generated by Django 2.2.2 on 2019-06-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20190627_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='Images'),
        ),
    ]
