# Generated by Django 2.2.2 on 2019-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20190628_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
