# Generated by Django 2.2.3 on 2019-07-18 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=300)),
                ('last_name', models.CharField(default='', max_length=300)),
                ('street', models.CharField(default='', max_length=300)),
                ('address', models.CharField(default='', max_length=300)),
                ('country', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=300)),
                ('zip', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('payment', models.CharField(choices=[('1', 'visa'), ('2', 'Bank wire'), ('3', 'Paypal')], max_length=1)),
                ('comments', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
